name: publish

on: [push]

jobs:
  build_libraries:
    runs-on: ${{ matrix.os.runner }}
    strategy:
      matrix:
        os:
          - runner: ubuntu-22.04
            type: linux
            platform: linux-amd64
          - runner: ubuntu-22.04-arm
#          - runner: buildjet-2vcpu-ubuntu-2204-arm
            type: linux
            platform: linux-arm64
          - runner: macos-latest
            type: macos
            platform: darwin-arm64
    steps:
      - uses: actions/checkout@v4
      - if: ${{ matrix.os.type == 'linux' }}
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 9
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle
      - name: java
        run: |
          ./gradlew publish -Pbranch=${{ github.ref_name }} -PdeployUser=${{ secrets.deploy_user }} -PdeployPassword=${{ secrets.deploy_password }}
